apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-03-07T18:44:59Z"
  labels:
    run: database
  name: database
  namespace: default
  resourceVersion: "1740"
  selfLink: /api/v1/namespaces/default/pods/database
  uid: 3b12b31d-833b-4c56-b405-e0ac0067b19d
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: Prason1234
    image: 168491602991.dkr.ecr.us-east-1.amazonaws.com/sqldb-repo:v1
    imagePullPolicy: IfNotPresent
    name: database
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-l7hqr
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: kind-control-plane
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-l7hqr
    secret:
      defaultMode: 420
      secretName: default-token-l7hqr
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-03-07T18:44:59Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-03-07T18:45:20Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-03-07T18:45:20Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-03-07T18:44:59Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://f6825cfdff3026bde27ec37088bf2d33cf004bc5d829f2fb57a28ce24361450c
    image: 168491602991.dkr.ecr.us-east-1.amazonaws.com/sqldb-repo:v1
    imageID: 168491602991.dkr.ecr.us-east-1.amazonaws.com/sqldb-repo@sha256:e6353bb6113e51fe6160a552d97c0d56ea7bb8b9e86ac0d4752578e003aa5c00
    lastState: {}
    name: database
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-03-07T18:45:20Z"
  hostIP: 172.18.0.2
  phase: Running
  podIP: 10.244.0.5
  podIPs:
  - ip: 10.244.0.5
  qosClass: BestEffort
  startTime: "2024-03-07T18:44:59Z"