apiVersion: v1
kind: Pod
metadata:
  labels:
    run: database
  name: database
  namespace: sqldb
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: Prason1234
    image: 168491602991.dkr.ecr.us-east-1.amazonaws.com/sqldb-repo:v1
    name: database
    resources: {}
    ports:
    - containerPort: 3306 
      protocol: TCP