apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-replicaset-v1
  namespace: webapp-replica
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
      version: v1
  template:
    metadata:
      labels:
        app: employees
        version: v1
    spec:
      containers:
      - name: webapp-v1
        image: 168491602991.dkr.ecr.us-east-1.amazonaws.com/webapp-repo:v1
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: 10.244.0.5
        - name: DBPWD
          value: Prason1234
        - name: DBPORT
          value: "3306"